project_id = "doyttekxvonlwmmxfezd"

[functions.api-complaints]
verify_jwt = false

[functions.send-whatsapp-meta]
verify_jwt = false

[functions.test-whatsapp-meta]
verify_jwt = false

[functions.whatsapp-meta-webhook]
verify_jwt = false

[functions.check-anomalies]
verify_jwt = true
